export enum UserRole {
  ADMIN = "ADMIN",
  EMPLOYEE = "EMPLOYEE",
  CUSTOMER = "CUSTOMER",
  SUPPLIER = "SUPPLIER",
  CARRIER = "CARRIER",
  COLLABORATOR = "COLLABORATOR",
  MANAGER = "MANAGER",
  TECHNICIAN = "TECHNICIAN",
}

